# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: News
    url: '#news'
    weight: 20
  - name: People
    url: '#people'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Events
    url: '#events'
    weight: 50
  - name: Teaching
    url: '#teaching'
    weight: 60
  - name: Theses
    url: '#theses'
    #pre: <div style="width:0px; height:0px">
    weight: 70    
  - name: Contact
    url: '#contact'
    weight: 80
    #pre: <div style="width:0px; height:0px">


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70

#  - url: https://www.unipd.it
#    weight: 100
#    pre:  <img src="img/logo-UNIPD-white.png" alt="Logo Unipd" style="float:bottom;width:30%">
    #pre:  <img src="img/logo-UNIPD-white.png" alt="Logo Unipd" style="width:50%">