# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
    pre: <br><br>
  - name: Research
    url: '#research'
    weight: 20
    pre: <br><br>
  - name: News
    url: '#news'
    weight: 30
    pre: <br><br>
  - name: People
    url: '#people'
    weight: 40
    pre: <br><br>
  - name: Collaborators
    url: '#externals'
    weight: 50
    pre: <br><br>
  - name: Publications
    url: '#publications'
    weight: 60
    pre: <br><br>
  - name: Events
    url: '#events'
    weight: 70
    pre: <br><br>
  - name: Teaching
    url: '#teaching'
    weight: 80
    pre: <br><br>
  # - name: Theses
  #   url: '#theses'
  #   weight: 70   
  #   pre: <br><br>   
  - name: Contact
    url: '#contact'
    weight: 90
    pre: <br><br>


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70

  - name: "&nbsp"
    url: https://www.unipd.it
    weight: 100
    pre:  <br><img src="/img/logo-UNIPD-white.png" alt="Logo Unipd" style="padding-left:70px; width:65%">
  - #name: "&nbsp"
    url: https://www.dfa.unipd.it
    weight: 150
    pre:  <br><img src="/img/logo_dfa_white.png" alt="Logo DFA" style="width:40%">
